### ISSUE TITLE
devtools::check()

### ISSUE THREAD

**Issue by fveitz** [TransBioInfoLab/coMethDMR#2] opened 2021-02-21 20:40 UTC
==> devtools::check()

Updating coMethDMR documentation
Loading coMethDMR
Warning in (function (dep_name, dep_ver = "*")  :
  Dependency package 'BiocParallel' not available.
Warning in (function (dep_name, dep_ver = "*")  :
  Dependency package 'bumphunter' not available.
Warning in (function (dep_name, dep_ver = "*")  :
  Dependency package 'GenomicRanges' not available.
Warning in (function (dep_name, dep_ver = "*")  :
  Dependency package 'IRanges' not available.
Error: Dependency package(s) 'BiocParallel','bumphunter','GenomicRanges','IRanges' not available.
Backtrace:
    x
 1. \-devtools::check(, check_dir = dirname(getwd()))
 2.   \-devtools::document(pkg, quiet = quiet)
 3.     +-withr::with_envvar(...)
 4.     | \-base::force(code)
 5.     \-roxygen2::roxygenise(pkg$path, roclets, load_code = load_code)
 6.       \-roxygen2:::load_code(base_path)
 7.         \-pkgload::load_all(path, helpers = FALSE, attach_testthat = FALSE)
 8.           \-pkgload:::load_imports(path)
 9.             \-pkgload:::abort_for_missing_packages(res, imports$package)
Execution halted

Exited with status 1.

**Comment by gabrielodom** [comment] 2021-02-22 00:51
This is a duplicate of Issue #1 .

**Closed by gabrielodom** 2021-02-22 00:51 UTC
Labels: bug
